#!/bin/bash

logpath="$(date --utc -Iseconds)"
upper_user="$(echo "$USER" | sed 's:.:\u&:')"

echo "     === Running backup on PHONE ==="
echo ""
echo "Current date is $(date)"
echo "Full backup log can be found at"
echo "  ~/media/backup/phone/rdiff-backup-data/backup.log"
echo "Historical backup logs can be found under ~/scripts/data/logs/"

echo "Mirroring phone to external"

rsync \
     --archive \
     --compress \
     --delete \
     --no-motd \
     --stats \
     --exclude DCIM/.thumbnails/ \
     --log-file "$HOME/scripts/data/logs/phone/$logpath-rsync-mirror" \
     phone:/sdcard/ ~/media/backup/phone/current

echo "=== Begin rdiff-backup ==="
echo ""

rm -f ~/media/backup/phone/rdiff-backup/rdiff-backup-data/backup.log

rdiff-backup \
    --terminal-verbosity 3 \
    --verbosity 5 \
    ~/media/backup/phone/current ~/media/backup/phone/rdiff-backup

echo "=== End rdiff-backup ==="

cp ~/media/backup/phone/rdiff-backup/rdiff-backup-data/backup.log \
   "$HOME/scripts/data/logs/phone/$logpath"

echo "=== Begin rsync ==="

rsync \
    --rsync-path=/bin/rsync \
    -a \
    --stats \
    --delete \
    --log-file "$HOME/scripts/data/logs/phone/$logpath-rsync" \
    ~/media/backup/phone/ "nas:/volume1/homes/$upper_user/backup/phone"

echo "=== End rsync ==="
