#!/bin/bash
upper_user="$(echo "$USER" | sed 's:.:\u&:')"
logpath="$(date --utc -Iseconds)"

echo "     === Running backup on HOMEDIR ==="
echo ""
echo "Current date is $(date)"
echo "Full rdiff-backup log can be found at"
echo "~/scripts/data/logs/homedir/$logpath-rdiff"
echo ""
echo "Full rsync mirror log can be found at"
echo "~/scripts/data/logs/homedir/$logpath-rsync"
echo ""
echo "=== Begin rdiff-backup ==="
echo ""

rm -f ~/media/backup/homedir/rdiff-backup-data/backup.log

rdiff-backup \
    --terminal-verbosity 3 \
    --verbosity 5 \
    --exclude ~/.local \
    --exclude ~/media \
    --exclude ~/.cache \
    --exclude ~/mount/NAS \
    --exclude ~/mount/usbstick \
    --exclude ~/dl \
    ~ ~/media/backup/homedir/

echo "=== End rdiff-backup ==="

echo ""

echo "=== Begin rsync ==="

rsync \
    --rsync-path=/bin/rsync \
    -a \
    --stats \
    --delete \
    --exclude media \
    --log-file "$HOME/scripts/data/logs/homedir/$logpath-rsync" \
    ~/media/backup/homedir/ "nas:/volume1/homes/$upper_user/backup/homedir"

echo "=== End rsync ==="

cp ~/media/backup/homedir/rdiff-backup-data/backup.log \
   "$HOME/scripts/data/logs/homedir/$logpath-rdiff"
