#!/bin/bash

upper_user="$(echo "$USER" | sed 's:.:\u&:')"

logpath="$(date --utc -Iseconds)"

echo "     === Running mirror on external ==="
echo ""
echo "Current date is $(date)"
echo "Full mirror log can be found at"
echo "  ~/scripts/data/logs/external/$logpath"

rsync \
    --rsync-path=/bin/rsync \
    -a \
    -z \
    --stats \
    --exclude backup \
    --log-file "$HOME/scripts/data/logs/external/$logpath" \
    ~/media "nas:/volume1/homes/$upper_user/backup"
