#!/bin/bash
echo "     === Running backup on PHONE ==="
echo ""
echo "Current date is $(date)"
echo "Full backup log can be found at"
echo "  ~/media/backup/phone/rdiff-backup-data/backup.log"
echo "Historical backup logs can be found under ~/scripts/data/logs/"

echo "Mirroring phone to external"

rsync \
     --archive \
     --compress \
     --delete \
     --no-motd \
     --stats \
     --exclude DCIM/.thumbnails/ \
     phone:/sdcard/ ~/media/backup/phone/current

echo "=== Begin rdiff-backup ==="
echo ""

rm -f ~/media/backup/phone/rdiff-backup/rdiff-backup-data/backup.log

rdiff-backup \
    --terminal-verbosity 3 \
    --verbosity 5 \
    ~/media/backup/phone/current ~/media/backup/phone/rdiff-backup

echo "=== End rdiff-backup ==="

cp ~/media/backup/phone/rdiff-backup/rdiff-backup-data/backup.log \
   ~/scripts/data/logs/phone/$(date --utc -Iseconds)
