#!/bin/sh -e
#
# Usage: browser
#        pipe html to a browser
# e.g.
#  $ echo '<h1>hi mom!</h1>' | browser
#  $ ron -5 man/rip.5.ron | browser   
# https://gist.github.com/defunkt/318247

if [ -t 0 ]; then
  if [ -n "$1" ]; then
    open "$1"
  else
    cat <<usage
Usage: browser
       pipe html to a browser
$ echo '<h1>hi mom!</h1>' | browser
$ ron -5 man/rip.5.ron | browser
usage
fi
else
  f=$(mktemp)
  cat /dev/stdin > "$f"
  firefox "$f"
fi
