#!/bin/python

import subprocess

def get_selection():
    return subprocess.check_output(["xsel"])

def get_clipboard():
    return subprocess.check_output(["xsel", "-b"])

def dmenu(choices=[], prompt="", multi=False, args=[]):
    cmd = DMENU

    cmd += " -p '{}'".format(prompt)

    if multi:
        args += ["-multi-select"]

    for arg in args:
        cmd += " {} ".format(arg)

    cmd = shlex.split(cmd)

    print(cmd)

    proc = subprocess.Popen(cmd, stdin=subprocess.PIPE, stdout=subprocess.PIPE)

    choice = proc.communicate("\n".join(choices).encode("UTF8"))[0].strip().decode("UTF8")

    if choice == "!kill":
        sys.exit(0)


    if multi:
        choices = choice.split("\n")
        return choices


    return choice


DMENU  = "rofi "
DMENU += "-dmenu "
DMENU += "-i "

sel = get_selection()
clip = get_clipboard()

cmds = []

cmds.append(sel.strip())
cmds.append(clip.strip())

print(cmds)
