#!/bin/bash

tmpfile="$(mktemp --suffix=.png)"

xclip -selection clipboard -t image/png -o > "$tmpfile"

gimp --new-instance "$tmpfile"

xclip -selection clipboard -t image/png -i "$tmpfile"

notify-send "Copied" "image copied to clipboard"
