#!/bin/bash

playlist_file=$(mktemp)

find "$(pwd)" -type f \(  \
    -name "*.mkv" \
\) | sort --numeric-sort | fzf --tiebreak=index --reverse -m > "$playlist_file"

mpv --playlist "$playlist_file"

rm "$playlist_file"
