#!/bin/bash

cd ~/sync/writings/notes || exit

case "$1" in

    "add")
        $EDITOR "${2:-$(date -Isecond)}"
        ;;

    "rm")
        rm "$2"
        ;;

    "cat")
        cat "$2"
        ;;

    "grep")
        if [ "$(ls | wc -l)" -gt 0 ]; then
            grep --color=auto -H "$2" *
        fi
        ;;

    "ls")
        if [ "$(ls | wc -l)" -gt 0 ]; then
            if ppipe -h 2>/dev/null; then
                stat --printf="%n\t%s\t%Z\n" ./* |\
                    ppipe -j "|" "[L[0]], H(L[1]), Ago(L[2])"|\
                    column -t -s "|" -o "    "
            else
                ls --sort=time
            fi
        fi
        ;;

    *)
        echo "Unknown command $1"
        note ls
        ;;

esac
