#!/usr/bin/env bash

export PASSWORD_STORE_X_SELECTION="primary"

shopt -s nullglob globstar

enter_user_pass() {
    sleep 1
    xdotool type --clearmodifiers "$1"
    xdotool key --clearmodifiers "Tab"
    xdotool type --clearmodifiers "$2"
}


prefix=${PASSWORD_STORE_DIR-~/.password-store}
password_files=( "$prefix"/**/*.gpg )
password_files=( "${password_files[@]#"$prefix"/}" )
password_files=( "${password_files[@]%.gpg}" )

password_name=$(printf '%s\n' "${password_files[@]}" | rofi -dmenu -p ": " -fuzzy "$@")
[[ -n $password_name ]] || exit

password=$(pass show "$password_name" | head -n1)
username=$(basename "$password_name")

todo=$(printf 'type userpass\ntype pass\nshow' | rofi -dmenu -p ": ")


if [[ "$todo" = "type userpass" ]]; then
    enter_user_pass "$username" "$password"
elif [[ "$todo" = "type pass" ]]; then
    xdotool type --clearmodifiers "$password"
elif [[ "$todo" = show ]]; then
    notify-send -t 2500000 "passwordstore" "Password: \"$password\""
fi
