#!/bin/bash

tmpfile="$(mktemp --suffix=.png)"

maim -f png -u -m 2 "$tmpfile"

gimp --new-instance "$tmpfile"

xclip -selection clipboard -t image/png -i "$tmpfile"

notify-send "Copied" "image copied to clipboard"
