#!/bin/bash

detect_regex="youtu|vimeo"
url="$(echo "$1" | htmlescape)"
notify-send "url-launcher" "Opening URL $url"

if echo "$1" | grep -E "$detect_regex"; then
    if youtube-dl --get-url "$1"; then
        mpv --fullscreen "$1"
    else
        qutebrowser "$1"&
    fi
else
    qutebrowser "$1"&
fi

