#!/bin/bash

case $BLOCK_BUTTON in
    1)
    if [ -e "/tmp/${DISPLAY}_neverlock" ]; then
        rm "/tmp/${DISPLAY}_neverlock"
    else
        touch "/tmp/${DISPLAY}_neverlock"
    fi
    ;;

    2)
        touch "/tmp/${DISPLAY}_lockmachine"
    ;;
esac

echo "L"
echo

if [ -e "/tmp/${DISPLAY}_neverlock" ]; then
    echo \#444444
fi
