#!/usr/bin/env bash

mail_count="$(find ~/mail/"$BLOCK_INSTANCE"/INBOX/new -type f | wc -l)"

case $BLOCK_BUTTON in
    3)
        notify-send "emails" "$(
        for f in ~/mail/$BLOCK_INSTANCE/INBOX/new/*
        do
            sed -n "s/Subject: \(.*\)/\1/p" < $f | \
            python -c "import sys,email.header;print(email.header.decode_header(sys.stdin.read())[0][0].decode('UTF-8'))"
        done)"
    ;;
esac

if [[ "$mail_count" -gt 0 ]]; then
    echo "$BLOCK_INSTANCE: $mail_count"
else
    echo ""
fi
