#!/bin/bash

readonly INTERVAL=30

echo "${BLOCK_INSTANCE:=eth0}" >/dev/null

old_tx="$(ip -j -s link show enp3s0 | jq '.[0].stats64.tx.bytes')"
old_rx="$(ip -j -s link show enp3s0 | jq '.[0].stats64.rx.bytes')"

sleep "$INTERVAL"

new_tx="$(ip -j -s link show enp3s0 | jq '.[0].stats64.tx.bytes')"
new_rx="$(ip -j -s link show enp3s0 | jq '.[0].stats64.rx.bytes')"

tx_rate=$(( ( new_tx - old_tx ) / 1024 / INTERVAL ))
rx_rate=$(( ( new_rx - old_rx ) / 1024 / INTERVAL ))

if [[ $rx_rate -gt 500 || $tx_rate -gt 200 ]]; then
    echo "$rx_rate/$tx_rate KB/s"
elif [[ $new_rx -eq $old_rx ]]; then
    echo "No internet?"
else
    echo ""
fi
