#!/bin/bash
count="$(pgrep -x "$BLOCK_INSTANCE" | wc -l)"

if [[ count -gt 0 ]]; then
    if [[ count -gt 1 ]]; then
        echo "$BLOCK_INSTANCE: $count"
    else
        echo "$BLOCK_INSTANCE"
    fi
fi
