#!/usr/bin/env bash

case $BLOCK_BUTTON in
3)
    notify-send "time" "$(date '+%Y-%m-%d %H:%M:%S  %Z (%:::z)')\n\
$(TZ=Universal date '+%Y-%m-%d %H:%M:%S  %Z (%:::z)')\n\
$(cal)"
;;
esac
date "+%a %d %b %Y %H:%M"
