directory: ~/media/music
library: ~/media/music/library.blb

import:
    write: yes
    copy: yes
    languages: en
    timid: no
    log: ~/media/music/beets-import.log

match:
    strong_rec_thresh: 0.01

plugins: 
    alternatives
    badfiles
    chroma
    convert
    edit
    fetchart
    fromfilename
    ftintitle
    fuzzy
    info
    inline
    lastgenre
    mbsync
    missing
    permissions
    replaygain
    rewrite
    scrub
    types
    zero

zero:
    fields: bpm acoustid_fingerprint initial_key month day

alternatives:
    phone:
        directory: ~/media/transcode
        formats: ogg
        query: ""

replaygain:
    auto: yes
    backend: gstreamer
    overwrite: yes

replace:
    '[\\/]': _
    '^\.': _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    '\.$': _
    '\s+$': ''
    '^\s+': ''
    '^-': _

asciify_paths: yes

pluginpath:
    ~/.config/beets/plugins

ui:
    color: yes
    colors:
        text_success: green
        text_warning: yellow
        text_error: red
        text_highlight: red
        text_highlight_minor: lightgray
        action_default: turquoise
        action: blue

original_date: true

convert:
    never_convert_lossy_files: no
    format: ogg
    dest: ~/media/transcode
    threads: 8
    quiet: true

types:
    on_phone: bool

edit:
    itemfields: track title artist album year month day

    albumfields: album albumartist year month day

paths:
    default: $albumartist/%if{$year,$year - }$album%aunique{}/%if{$track,$track - }$title
    singleton: $albumartist/Singles/$title
    comp: Various Artists/$album%aunique{}/%if{$track,$track - }$title
